// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_MLD.Models;

#nullable disable

namespace Project_MLD.Migrations
{
    [DbContext(typeof(MldDatabaseContext))]
    [Migration("20240406134357_Migration_v3")]
    partial class Migration_v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_100_CI_AS_SC_UTF8")
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project_MLD.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateOnly?>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("created_date");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("AccountId");

                    b.HasIndex("RoleId");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GradeId")
                        .HasColumnType("int")
                        .HasColumnName("grade_ id");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id")
                        .HasName("PK_Lớp");

                    b.HasIndex("GradeId");

                    b.ToTable("Class", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.CurriculumDistribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id")
                        .HasName("PK_Phân phối chương trình");

                    b.ToTable("Curriculum Distribution", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.Doc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("content");

                    b.Property<int>("Document4Id")
                        .HasColumnType("int")
                        .HasColumnName("document4_id");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id")
                        .HasName("PK_Document");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Document4Id");

                    b.ToTable("Doc", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.Document1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApproveBy")
                        .HasColumnType("int")
                        .HasColumnName("approve_by");

                    b.Property<int?>("GradeId")
                        .HasColumnType("int")
                        .HasColumnName("grade_id");

                    b.Property<bool?>("IsApprove")
                        .HasColumnType("bit")
                        .HasColumnName("isApprove");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_Kế Hoạch Dạy Học");

                    b.HasIndex("GradeId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Document 1", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.Document1CurriculumDistribution", b =>
                {
                    b.Property<int>("CurriculumId")
                        .HasColumnType("int")
                        .HasColumnName("curriculum_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("Document1Id")
                        .HasColumnType("int")
                        .HasColumnName("document1_id");

                    b.Property<int>("Slot")
                        .HasColumnType("int")
                        .HasColumnName("slot");

                    b.HasIndex("CurriculumId");

                    b.HasIndex("Document1Id");

                    b.ToTable("Document1_CurriculumDistribution", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.Document1SelectedTopic", b =>
                {
                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("Document1Id")
                        .HasColumnType("int")
                        .HasColumnName("document1_id");

                    b.Property<int?>("SelectedTopicsId")
                        .HasColumnType("int")
                        .HasColumnName("selected_topics_id");

                    b.Property<int?>("Slot")
                        .HasColumnType("int")
                        .HasColumnName("slot");

                    b.HasIndex("Document1Id");

                    b.HasIndex("SelectedTopicsId");

                    b.ToTable("Document1_SelectedTopics", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.Document1SubjectRoom", b =>
                {
                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("Document1Id")
                        .HasColumnType("int")
                        .HasColumnName("document1_id");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int?>("SubjectRoomId")
                        .HasColumnType("int")
                        .HasColumnName("subject_room_id");

                    b.HasIndex("Document1Id");

                    b.HasIndex("SubjectRoomId");

                    b.ToTable("Document1_Subject Room", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.Document1TeachingEquipment", b =>
                {
                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("Document1Id")
                        .HasColumnType("int")
                        .HasColumnName("document1_id");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int?>("TeachingEquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("teaching_equipment_id");

                    b.HasIndex("Document1Id");

                    b.HasIndex("TeachingEquipmentId");

                    b.ToTable("Document1_TeachingEquipment", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.Document2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApproveBy")
                        .HasColumnType("int")
                        .HasColumnName("approve_by");

                    b.Property<bool?>("IsApprove")
                        .HasColumnType("bit")
                        .HasColumnName("isApprove");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_Kế hoạch Tổ chức Hoạt Động Giáo Dục");

                    b.HasIndex("UserId");

                    b.ToTable("Document 2", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.Document2Grade", b =>
                {
                    b.Property<string>("CollaborateWith")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("collaborate_with")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("condition")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("Document2Id")
                        .HasColumnType("int")
                        .HasColumnName("document2_id");

                    b.Property<int?>("GradeId")
                        .HasColumnType("int")
                        .HasColumnName("grade_id");

                    b.Property<string>("HostBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("host_by")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("place")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("Slot")
                        .HasColumnType("int")
                        .HasColumnName("slot");

                    b.Property<DateOnly?>("Time")
                        .HasColumnType("date")
                        .HasColumnName("time");

                    b.Property<string>("TitleName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title_name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasIndex("Document2Id");

                    b.HasIndex("GradeId");

                    b.ToTable("Document2_Grade", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.Document3", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApproveBy")
                        .HasColumnType("int")
                        .HasColumnName("approve_by");

                    b.Property<int?>("Document1Id")
                        .HasColumnType("int")
                        .HasColumnName("document1_id");

                    b.Property<bool?>("IsApprove")
                        .HasColumnType("bit")
                        .HasColumnName("isApprove");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_Kế hoạch giáo dục của GV");

                    b.HasIndex("Document1Id");

                    b.HasIndex("UserId");

                    b.ToTable("Document 3", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.Document4", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<int?>("TeachingPlannerId")
                        .HasColumnType("int")
                        .HasColumnName("teaching_planner_id");

                    b.HasKey("Id")
                        .HasName("PK_Phu Luc 4");

                    b.HasIndex("TeachingPlannerId");

                    b.ToTable("Document 4", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.Document5", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Document4Id")
                        .HasColumnType("int")
                        .HasColumnName("document4_id");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("Total")
                        .HasColumnType("int")
                        .HasColumnName("total");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_Phu Luc 5");

                    b.HasIndex("Document4Id");

                    b.HasIndex("UserId");

                    b.ToTable("Document 5", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.FormCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id")
                        .HasName("PK_Hình thức thi");

                    b.ToTable("Form Category", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("TotalStudent")
                        .HasColumnType("int")
                        .HasColumnName("total_student");

                    b.Property<int?>("TotalStudentSelectedTopics")
                        .HasColumnType("int")
                        .HasColumnName("total_student_selected_topics");

                    b.HasKey("Id")
                        .HasName("PK_Khối Lớp");

                    b.ToTable("Grade", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.LevelOfTrainning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id")
                        .HasName("PK_LevelOfTrainning");

                    b.ToTable("Level Of Trainning", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.PeriodicAssessment", b =>
                {
                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("Document1Id")
                        .HasColumnType("int")
                        .HasColumnName("document1_id");

                    b.Property<int?>("FormCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("form_category_id");

                    b.Property<int?>("TestingCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("testing_category_id");

                    b.Property<int?>("Time")
                        .HasColumnType("int")
                        .HasColumnName("time");

                    b.HasIndex("Document1Id");

                    b.HasIndex("FormCategoryId");

                    b.HasIndex("TestingCategoryId");

                    b.ToTable("Periodic Assessment", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.ProfessionalStandard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id");

                    b.ToTable("Professional Standards", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role_name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("RoleId");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.SelectedTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id")
                        .HasName("PK_Chuyên đề / Bài Học");

                    b.ToTable("Selected Topics", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.SpecializedDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id")
                        .HasName("PK_Tổ chuyên Môn");

                    b.ToTable("Specialized Department", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id")
                        .HasName("PK_Môn học");

                    b.ToTable("Subject", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.SubjectRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id")
                        .HasName("PK_Phòng Bộ Môn");

                    b.ToTable("Subject Room", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.TeachingEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id")
                        .HasName("PK_Thiết bị dậy học");

                    b.ToTable("Teaching Equipment", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.TeachingPlanner", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_User - Lớp - Mon");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Teaching Planner", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.TestingCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id")
                        .HasName("PK_Loại Bài kiểm tra");

                    b.ToTable("Testing Category", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("active");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("created_by")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateOnly?>("CreatedDate")
                        .HasColumnType("date")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("full_name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("LevelOfTrainningId")
                        .HasColumnType("int")
                        .HasColumnName("level_of_trainning_id");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int")
                        .HasColumnName("modified_by");

                    b.Property<DateOnly?>("ModifiedDate")
                        .HasColumnType("date")
                        .HasColumnName("modified_date");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("photo");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("place_of_birth")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int?>("ProfessionalStandardsId")
                        .HasColumnType("int")
                        .HasColumnName("professional_standards_id");

                    b.Property<int?>("SpecializedDepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("specialized_department_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("LevelOfTrainningId");

                    b.HasIndex("ProfessionalStandardsId");

                    b.HasIndex("SpecializedDepartmentId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Project_MLD.Models.Account", b =>
                {
                    b.HasOne("Project_MLD.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_Account_Role1");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Project_MLD.Models.Class", b =>
                {
                    b.HasOne("Project_MLD.Models.Grade", "Grade")
                        .WithMany("Classes")
                        .HasForeignKey("GradeId")
                        .HasConstraintName("FK_Class_Grade");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("Project_MLD.Models.Doc", b =>
                {
                    b.HasOne("Project_MLD.Models.Category", "Category")
                        .WithMany("Docs")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Doc_Category");

                    b.HasOne("Project_MLD.Models.Document4", "Document4")
                        .WithMany("Docs")
                        .HasForeignKey("Document4Id")
                        .IsRequired()
                        .HasConstraintName("FK_Doc_Document 4");

                    b.Navigation("Category");

                    b.Navigation("Document4");
                });

            modelBuilder.Entity("Project_MLD.Models.Document1", b =>
                {
                    b.HasOne("Project_MLD.Models.Grade", "Grade")
                        .WithMany("Document1s")
                        .HasForeignKey("GradeId")
                        .HasConstraintName("FK_Document 1_Grade");

                    b.HasOne("Project_MLD.Models.Subject", "Subject")
                        .WithMany("Document1s")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK_Document 1_Subject");

                    b.HasOne("Project_MLD.Models.User", "User")
                        .WithMany("Document1s")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Phu Luc 1_User");

                    b.Navigation("Grade");

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project_MLD.Models.Document1CurriculumDistribution", b =>
                {
                    b.HasOne("Project_MLD.Models.CurriculumDistribution", "Curriculum")
                        .WithMany()
                        .HasForeignKey("CurriculumId")
                        .IsRequired()
                        .HasConstraintName("FK_Document1_CurriculumDistribution_Curriculum Distribution");

                    b.HasOne("Project_MLD.Models.Document1", "Document1")
                        .WithMany()
                        .HasForeignKey("Document1Id")
                        .IsRequired()
                        .HasConstraintName("FK_Document1_CurriculumDistribution_Document 1");

                    b.Navigation("Curriculum");

                    b.Navigation("Document1");
                });

            modelBuilder.Entity("Project_MLD.Models.Document1SelectedTopic", b =>
                {
                    b.HasOne("Project_MLD.Models.Document1", "Document1")
                        .WithMany()
                        .HasForeignKey("Document1Id")
                        .HasConstraintName("FK_Document1_SelectedTopics_Document 1");

                    b.HasOne("Project_MLD.Models.SelectedTopic", "SelectedTopics")
                        .WithMany()
                        .HasForeignKey("SelectedTopicsId")
                        .HasConstraintName("FK_Document1_SelectedTopics_Selected Topics");

                    b.Navigation("Document1");

                    b.Navigation("SelectedTopics");
                });

            modelBuilder.Entity("Project_MLD.Models.Document1SubjectRoom", b =>
                {
                    b.HasOne("Project_MLD.Models.Document1", "Document1")
                        .WithMany()
                        .HasForeignKey("Document1Id")
                        .HasConstraintName("FK_Document1_Subject Room_Document 1");

                    b.HasOne("Project_MLD.Models.SubjectRoom", "SubjectRoom")
                        .WithMany()
                        .HasForeignKey("SubjectRoomId")
                        .HasConstraintName("FK_Document1_Subject Room_Subject Room");

                    b.Navigation("Document1");

                    b.Navigation("SubjectRoom");
                });

            modelBuilder.Entity("Project_MLD.Models.Document1TeachingEquipment", b =>
                {
                    b.HasOne("Project_MLD.Models.Document1", "Document1")
                        .WithMany()
                        .HasForeignKey("Document1Id")
                        .HasConstraintName("FK_Document1_TeachingEquipment_Document 1");

                    b.HasOne("Project_MLD.Models.TeachingEquipment", "TeachingEquipment")
                        .WithMany()
                        .HasForeignKey("TeachingEquipmentId")
                        .HasConstraintName("FK_Document1_TeachingEquipment_Teaching Equipment");

                    b.Navigation("Document1");

                    b.Navigation("TeachingEquipment");
                });

            modelBuilder.Entity("Project_MLD.Models.Document2", b =>
                {
                    b.HasOne("Project_MLD.Models.User", "User")
                        .WithMany("Document2s")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Kế hoạch Tổ chức Hoạt Động Giáo Dục_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project_MLD.Models.Document2Grade", b =>
                {
                    b.HasOne("Project_MLD.Models.Document2", "Document2")
                        .WithMany()
                        .HasForeignKey("Document2Id")
                        .HasConstraintName("FK_Document2_Grade_Document 2");

                    b.HasOne("Project_MLD.Models.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .HasConstraintName("FK_Document2_Grade_Grade");

                    b.Navigation("Document2");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("Project_MLD.Models.Document3", b =>
                {
                    b.HasOne("Project_MLD.Models.Document1", "Document1")
                        .WithMany("Document3s")
                        .HasForeignKey("Document1Id")
                        .HasConstraintName("FK_Document 3_Document 1");

                    b.HasOne("Project_MLD.Models.User", "User")
                        .WithMany("Document3s")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Document 3_User");

                    b.Navigation("Document1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project_MLD.Models.Document4", b =>
                {
                    b.HasOne("Project_MLD.Models.TeachingPlanner", "TeachingPlanner")
                        .WithMany("Document4s")
                        .HasForeignKey("TeachingPlannerId")
                        .HasConstraintName("FK_Document 4_Teaching Planner");

                    b.Navigation("TeachingPlanner");
                });

            modelBuilder.Entity("Project_MLD.Models.Document5", b =>
                {
                    b.HasOne("Project_MLD.Models.Document4", "Document4")
                        .WithMany("Document5s")
                        .HasForeignKey("Document4Id")
                        .IsRequired()
                        .HasConstraintName("FK_Document 5_Document 4");

                    b.HasOne("Project_MLD.Models.User", "User")
                        .WithMany("Document5s")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Document 5_User");

                    b.Navigation("Document4");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project_MLD.Models.Feedback", b =>
                {
                    b.HasOne("Project_MLD.Models.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Feedback_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project_MLD.Models.PeriodicAssessment", b =>
                {
                    b.HasOne("Project_MLD.Models.Document1", "Document1")
                        .WithMany()
                        .HasForeignKey("Document1Id")
                        .HasConstraintName("FK_Periodic Assessment_Document 1");

                    b.HasOne("Project_MLD.Models.FormCategory", "FormCategory")
                        .WithMany()
                        .HasForeignKey("FormCategoryId")
                        .HasConstraintName("FK_Periodic Assessment_Form Category");

                    b.HasOne("Project_MLD.Models.TestingCategory", "TestingCategory")
                        .WithMany()
                        .HasForeignKey("TestingCategoryId")
                        .HasConstraintName("FK_Periodic Assessment_Testing Category");

                    b.Navigation("Document1");

                    b.Navigation("FormCategory");

                    b.Navigation("TestingCategory");
                });

            modelBuilder.Entity("Project_MLD.Models.TeachingPlanner", b =>
                {
                    b.HasOne("Project_MLD.Models.Class", "Class")
                        .WithMany("TeachingPlanners")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_Teaching Planner_Class");

                    b.HasOne("Project_MLD.Models.Subject", "Subject")
                        .WithMany("TeachingPlanners")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK_Teaching Planner_Subject");

                    b.HasOne("Project_MLD.Models.User", "User")
                        .WithMany("TeachingPlanners")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Teaching Planner_User");

                    b.Navigation("Class");

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project_MLD.Models.User", b =>
                {
                    b.HasOne("Project_MLD.Models.Account", "Account")
                        .WithMany("Users")
                        .HasForeignKey("AccountId")
                        .HasConstraintName("FK_User_Account");

                    b.HasOne("Project_MLD.Models.LevelOfTrainning", "LevelOfTrainning")
                        .WithMany("Users")
                        .HasForeignKey("LevelOfTrainningId")
                        .HasConstraintName("FK_User_Level Of Trainning");

                    b.HasOne("Project_MLD.Models.ProfessionalStandard", "ProfessionalStandards")
                        .WithMany("Users")
                        .HasForeignKey("ProfessionalStandardsId")
                        .HasConstraintName("FK_User_Professional Standards");

                    b.HasOne("Project_MLD.Models.SpecializedDepartment", "SpecializedDepartment")
                        .WithMany("Users")
                        .HasForeignKey("SpecializedDepartmentId")
                        .HasConstraintName("FK_User_Specialized Department");

                    b.Navigation("Account");

                    b.Navigation("LevelOfTrainning");

                    b.Navigation("ProfessionalStandards");

                    b.Navigation("SpecializedDepartment");
                });

            modelBuilder.Entity("Project_MLD.Models.Account", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Project_MLD.Models.Category", b =>
                {
                    b.Navigation("Docs");
                });

            modelBuilder.Entity("Project_MLD.Models.Class", b =>
                {
                    b.Navigation("TeachingPlanners");
                });

            modelBuilder.Entity("Project_MLD.Models.Document1", b =>
                {
                    b.Navigation("Document3s");
                });

            modelBuilder.Entity("Project_MLD.Models.Document4", b =>
                {
                    b.Navigation("Docs");

                    b.Navigation("Document5s");
                });

            modelBuilder.Entity("Project_MLD.Models.Grade", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Document1s");
                });

            modelBuilder.Entity("Project_MLD.Models.LevelOfTrainning", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Project_MLD.Models.ProfessionalStandard", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Project_MLD.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Project_MLD.Models.SpecializedDepartment", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Project_MLD.Models.Subject", b =>
                {
                    b.Navigation("Document1s");

                    b.Navigation("TeachingPlanners");
                });

            modelBuilder.Entity("Project_MLD.Models.TeachingPlanner", b =>
                {
                    b.Navigation("Document4s");
                });

            modelBuilder.Entity("Project_MLD.Models.User", b =>
                {
                    b.Navigation("Document1s");

                    b.Navigation("Document2s");

                    b.Navigation("Document3s");

                    b.Navigation("Document5s");

                    b.Navigation("Feedbacks");

                    b.Navigation("TeachingPlanners");
                });
#pragma warning restore 612, 618
        }
    }
}
